spring.application.name=fitlite-backend
spring.datasource.url=jdbc:postgresql://localhost:5433/fitlite_db
spring.datasource.username=fitlite_user
spring.datasource.password=fitlite_pass
spring.datasource.driver-class-name=org.postgresql.Driver
server.port=8081

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true